### ISSUE TITLE
[Feature]: support mask blur when inpaint

### ISSUE THREAD

**Issue by DESEOUMAIGA** [VoltaML/voltaML-fast-stable-diffusion#157]
### Is your feature request related to a problem? Please describe.

1、When I do inpainting, there is no mask blur option, which results in the generated image not blending into the original image at the edges of the inpainted area.
![35817c8b-6056-44dd-a431-cbefd99f5cf8](https://github.com/VoltaML/voltaML-fast-stable-diffusion/assets/41180688/abf0036f-fc63-4f89-8adb-c10316ed93a4)
2、By the way, I would like to ask if it is possible to use ControlNet to control the inpainting process through the API or directly in the UI interface?

### Describe the solution you'd like

Perhaps the option to add mask blur could be considered?

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
1. Not currently possible in Volta, but I will look into implementing it when my free time frees up a bit.
2. Due to the number of inputs for Inpainting controlnet, it is not possible in both UI or API. Same as number 1, would be great to have and we will put it on our todo list, but we also have a life (and school), so it might take some time or might not show up at all. We just don't know what our situation will be.

Thanks for pointing some of these issues out. Leaving open as a TODO reminder.
