### ISSUE TITLE
mount directory of Local models already downloaded and allow civitai downloads

### ISSUE THREAD

**Issue by scruffynerf** [VoltaML/voltaML-fast-stable-diffusion#38]
wanting to compare to a1111, and I have a ton of models downloaded... but I see no way to mount a model directory so I can use them.
Also I often prefer civitai to huggingface.

Also if the TensorRT conversion is done locally, I'd like to save those and be able to reuse them... again, external mounted directory?

**Comment by Stax124** [comment]
`experimental` has a way to convert a .ckpt or .safetensors into the required structure so that you can use models from CivitAI as well, but, if you just want to use the file as is, then there is no way. It needs to be converted first.

`experimental` also has a way to mount huggingface cache and we can also mount the `converted` folder.

TRT engines are saved locally in the engine directory so you can reuse them.

**Comment by maxhille** [comment]
> `experimental` has a way to convert a .ckpt or .safetensors into the required structure so that you can use models from CivitAI as well, but, if you just want to use the file as is, then there is no way. It needs to be converted first.

Let's say I have a local `safetensor` file and want to convert it for VoltaML. So how would I do that?

Also, maybe this issue should not be closed.
