### ISSUE TITLE
MPS supporting

### ISSUE THREAD

**Issue by kstroevsky** [VoltaML/voltaML-fast-stable-diffusion#50]
### Is your feature request related to a problem? Please describe.

What do you think to add Apple MPS supporting? Will be it useful or even possible with voltaML architecture?

### Describe the solution you'd like

Pytorch is supporting [MPS backend](https://developer.apple.com/documentation/metalperformanceshaders) for low-level Apple Silicon GPU accelerating.

### Additional context

Device: Macbook M1 Pro Max
OS: MacOS Ventura

### Validations

- [X] Read the [docs](https://voltaml.github.io/voltaML-fast-stable-diffusion/).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by Stax124** [comment]
Hi, AITemplate acceleration functions only on Nvidia and (some) AMD GPUs, so that is a dead end, but, I can try adding support for running on MPS at least for our PyTorch backend (but I will have no way to test it as I do not own any Apple product - and that will most certainly be the case in the future as well).

Some people saw a speed uplift even on PyTorch when compared to A111, so you might see some benefit there, but I cannot promise a single thing here.

**Comment by Stax124** [comment]
Volta should now technically support MPS, but, as I said, I do not own a MacBook. You can try running it on the experimental branch. All you need to do is start the API, go to http://localhost:5003, Settings->API->Device->Device Type, and set that to MPS (Apple), then just save the settings

![image](https://user-images.githubusercontent.com/60222162/230606840-a7f1f3e1-d866-4022-ba1d-fcaf2e775d31.png)

![image](https://user-images.githubusercontent.com/60222162/230606896-54754836-d348-4835-8c0f-2dc6a68a1a27.png)

I expect a lot of bugs and errors, but I cannot do anything without having that hardware. Feel free to report those bugs, or maybe join our Discord server (link in Readme) and chat with me there.
